#!/bin/bash
## WORKAROUND DE UN BUG DE UBUNTU 14.04 QUE NO RESTAURABA EL BRILLO DE LA PANTALLA DEL PC PORTÁTIL CORRECTAMENTE AL REINICIAR 
### (guardado de valor de brillo en reinicio)
## FECHA: 30 de abril de 2016

echo "Guardando brillo..."
cat /sys/class/backlight/acpi_video0/brightness > /home/usuario/Comandos/brillo-guardado
exit 0
