#!/system/bin/sh
## WORKAROUND PARA ANDROID 4.4 x86 PARA ARMATOSTE: ESTABLECER VALOR ARBITRARIO PARA EL BRILLO
## FECHA: 28 de junio de 2016

echo "Introduce un número del 0 al 7. 0 es el brillo más bajo, y 7 es el más alto"
read BRILLO
echo $BRILLO > /sys/class/backlight/acpi_video0/brightness
exit 0
